#!/usr/bin/env python3
"""Offline C0 graph solver for witset graph snapshots."""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any


@dataclass
class SolverWeights:
    dict_weight: float = 1.0
    vertex_risk_weight: float = 12.0
    edge_risk_weight: float = 24.0
    ambiguous_edge_penalty: float = 6.0
    single_char_penalty: float = 0.35
    multi_char_bonus: float = 0.18
    ctx_total_weight: float = 0.55
    ctx_avg_weight: float = 0.18
    ctx_oov_penalty: float = 0.65
    ctx_fallback_penalty: float = 0.45
    ctx_whole_word_bonus: float = 0.12
    ctx_rerank_scale: float = 0.15
    ctx_rerank_margin: float = 12.0
    ctx_local_scale: float = 0.10
    ctx_local_base_margin: float = 2.5
    ctx_local_gain_threshold: float = 0.30


@dataclass
class PathSegment:
    start: int
    end: int
    word: str
    dict_weight: float
    edge_risk: float
    edge_spelling_class: int
    vertex_risk: float
    is_rear: bool


@dataclass
class PathState:
    score: float
    text: str
    words: list[str]
    debug_parts: list[str]
    segments: list[PathSegment] = field(default_factory=list)
    context_suffix: str = ""
    last_word_len_class: int = 0
    trailing_single_char_run: int = 0
    recent_len_signature: str = ""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run the minimal offline C0 graph solver over exported witset graphs."
    )
    parser.add_argument(
        "--graph",
        default=r"c:\Users\Bing\AppData\Roaming\witty\debug\witset_local_snapshot.graph.jsonl",
        help="Path to the exported graph JSONL file.",
    )
    parser.add_argument(
        "--reference",
        default=r"c:\Users\Bing\AppData\Roaming\witty\debug\snapshot_summary\reference_cases.jsonl",
        help="Path to reference_cases.jsonl generated by the local snapshot baseline.",
    )
    parser.add_argument(
        "--output-json",
        default=r"c:\Users\Bing\AppData\Roaming\witty\debug\snapshot_summary\c0_graph_solver_summary.json",
        help="Path to write the JSON summary.",
    )
    parser.add_argument(
        "--output-md",
        default=r"c:\Users\Bing\AppData\Roaming\witty\debug\snapshot_summary\c0_graph_solver_report.md",
        help="Path to write the markdown summary.",
    )
    parser.add_argument(
        "--limit",
        type=int,
        help="Optional limit of reference cases to evaluate.",
    )
    parser.add_argument(
        "--input",
        help="Optional exact raw input filter.",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=8,
        help="How many states to keep per position.",
    )
    parser.add_argument(
        "--solver",
        choices=[
            "c0",
            "c0_ctx",
            "c0_ctx_rerank",
            "c0_ctx_local",
            "c0_ctx_local_top1",
            "c01",
            "c01_state_only",
        ],
        default="c0",
        help="Solver variant. c01 keeps small path states instead of plain top-k per position.",
    )
    return parser.parse_args()


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line:
                continue
            payload = json.loads(line)
            if isinstance(payload, dict):
                records.append(payload)
    return records


def iter_jsonl_records(path: Path) -> Any:
    with path.open("r", encoding="utf-8", errors="replace") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line:
                continue
            json_start = line.find("{")
            if json_start > 0:
                line = line[json_start:]
            try:
                payload = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(payload, dict):
                yield payload


def utf8_char_count(text: str) -> int:
    return len(text)


def build_context_suffix(previous_suffix: str, word: str, token_limit: int) -> str:
    if token_limit <= 0:
        return ""
    tokens = list(previous_suffix) + list(word)
    if len(tokens) > token_limit:
        tokens = tokens[-token_limit:]
    return "".join(tokens)


def length_class(char_count: int) -> int:
    if char_count <= 1:
        return 1
    if char_count == 2:
        return 2
    return 3


def update_recent_len_signature(previous_signature: str, current_class: int) -> str:
    parts = [part for part in previous_signature.split("-") if part]
    parts.append(str(current_class))
    return "-".join(parts[-2:])


def score_word_edge(
    candidate: dict[str, Any],
    edge_risk: float,
    edge_spelling_class: int,
    vertex_risk: float,
    weights: SolverWeights,
) -> tuple[float, str]:
    text = str(candidate.get("text", ""))
    char_count = max(1, utf8_char_count(text))
    dict_weight = float(candidate.get("weight", 0.0))
    score = dict_weight * weights.dict_weight
    score -= edge_risk * weights.edge_risk_weight
    score -= vertex_risk * weights.vertex_risk_weight
    if edge_spelling_class >= 4:
        score -= weights.ambiguous_edge_penalty
    if char_count == 1:
        score -= weights.single_char_penalty
    else:
        score += weights.multi_char_bonus * float(char_count - 1)
    debug = (
        f"text={text} dict={dict_weight:.3f} edge_risk={edge_risk:.3f} "
        f"vertex_risk={vertex_risk:.3f} class={edge_spelling_class} "
        f"chars={char_count} score={score:.3f}"
    )
    return score, debug


def make_transition_key(context_suffix: str, word: str, is_rear: bool) -> tuple[str, str, bool]:
    return (context_suffix, word, is_rear)


def score_transition_context(
    transition_record: dict[str, Any] | None,
    weights: SolverWeights,
) -> tuple[float, str]:
    if not transition_record:
        return 0.0, "ctx=missing"
    if not bool(transition_record.get("has_lm_features", False)):
        return 0.0, "ctx=none"
    total_log10 = float(transition_record.get("total_log10", 0.0) or 0.0)
    avg_log10 = float(transition_record.get("avg_log10", 0.0) or 0.0)
    oov_token_count = int(transition_record.get("oov_token_count", 0) or 0)
    used_char_fallback = bool(transition_record.get("used_char_fallback", False))
    matched_whole_word = bool(transition_record.get("matched_whole_word", False))
    score = total_log10 * weights.ctx_total_weight
    score += avg_log10 * weights.ctx_avg_weight
    score -= float(oov_token_count) * weights.ctx_oov_penalty
    if used_char_fallback:
        score -= weights.ctx_fallback_penalty
    if matched_whole_word:
        score += weights.ctx_whole_word_bonus
    debug = (
        f"ctx_total={total_log10:.3f} ctx_avg={avg_log10:.3f} "
        f"ctx_oov={oov_token_count} ctx_fb={int(used_char_fallback)} "
        f"ctx_whole={int(matched_whole_word)} ctx_score={score:.3f}"
    )
    return score, debug


def build_transition_lm_index(
    record: dict[str, Any],
) -> tuple[dict[tuple[str, str, bool], dict[str, Any]], int]:
    context_token_limit = int(record.get("context_token_limit", 0) or 0)
    transition_lm_index: dict[tuple[str, str, bool], dict[str, Any]] = {}
    for transition in record.get("transition_lm_features", []):
        if not isinstance(transition, dict):
            continue
        key = make_transition_key(
            str(transition.get("context_suffix", "")),
            str(transition.get("word", "")),
            bool(transition.get("is_rear", False)),
        )
        transition_lm_index[key] = transition
    return transition_lm_index, context_token_limit


def build_word_edges_by_start(record: dict[str, Any]) -> dict[int, list[dict[str, Any]]]:
    word_edges_by_start: dict[int, list[dict[str, Any]]] = {}
    for edge in record.get("word_edges", []):
        if not isinstance(edge, dict):
            continue
        word_edges_by_start.setdefault(int(edge.get("start", 0) or 0), []).append(edge)
    return word_edges_by_start


def score_transition_with_presence(
    transition_lm_index: dict[tuple[str, str, bool], dict[str, Any]],
    context_suffix: str,
    word: str,
    is_rear: bool,
    weights: SolverWeights,
) -> tuple[float, str, bool]:
    record = transition_lm_index.get(make_transition_key(context_suffix, word, is_rear))
    score, debug = score_transition_context(record, weights)
    has_features = bool(record and record.get("has_lm_features", False))
    return score, debug, has_features


def apply_local_context_substitutions(
    state: PathState,
    word_edges_by_start: dict[int, list[dict[str, Any]]],
    transition_lm_index: dict[tuple[str, str, bool], dict[str, Any]],
    context_token_limit: int,
    weights: SolverWeights,
    require_nonnegative_base_diff: bool = False,
) -> PathState:
    if not state.segments:
        return state
    updated_words: list[str] = []
    updated_segments: list[PathSegment] = []
    debug_parts = list(state.debug_parts)
    total_gain = 0.0
    context_suffix = ""
    segment_count = len(state.segments)
    for index, segment in enumerate(state.segments):
        edge = None
        for candidate_edge in word_edges_by_start.get(segment.start, []):
            if int(candidate_edge.get("end", segment.start) or segment.start) == segment.end:
                edge = candidate_edge
                break
        if edge is None:
            updated_words.append(segment.word)
            updated_segments.append(segment)
            context_suffix = build_context_suffix(
                context_suffix, segment.word, context_token_limit
            )
            continue
        chosen_candidate = {"text": segment.word, "weight": segment.dict_weight}
        chosen_base, _ = score_word_edge(
            chosen_candidate,
            segment.edge_risk,
            segment.edge_spelling_class,
            segment.vertex_risk,
            weights,
        )
        chosen_curr_ctx, _, chosen_curr_has = score_transition_with_presence(
            transition_lm_index,
            context_suffix,
            segment.word,
            segment.is_rear,
            weights,
        )
        next_word = state.segments[index + 1].word if index + 1 < segment_count else ""
        next_is_rear = bool(index + 1 == segment_count - 1)
        chosen_next_suffix = build_context_suffix(
            context_suffix, segment.word, context_token_limit
        )
        chosen_next_ctx = 0.0
        chosen_next_has = False
        if next_word:
            chosen_next_ctx, _, chosen_next_has = score_transition_with_presence(
                transition_lm_index,
                chosen_next_suffix,
                next_word,
                next_is_rear,
                weights,
            )
        chosen_total_ctx = chosen_curr_ctx + chosen_next_ctx
        chosen_has_signal = chosen_curr_has or chosen_next_has
        best_word = segment.word
        best_dict_weight = segment.dict_weight
        best_gain = 0.0
        best_debug = "local_ctx keep=no_better_alt"
        candidates = edge.get("candidates", [])
        if isinstance(candidates, list):
            chosen_char_count = utf8_char_count(segment.word)
            for candidate in candidates:
                if not isinstance(candidate, dict):
                    continue
                alt_word = str(candidate.get("text", ""))
                if not alt_word or alt_word == segment.word:
                    continue
                if utf8_char_count(alt_word) != chosen_char_count:
                    continue
                alt_base, _ = score_word_edge(
                    candidate,
                    segment.edge_risk,
                    segment.edge_spelling_class,
                    segment.vertex_risk,
                    weights,
                )
                if require_nonnegative_base_diff and alt_base < chosen_base:
                    continue
                if alt_base < chosen_base - weights.ctx_local_base_margin:
                    continue
                alt_curr_ctx, _, alt_curr_has = score_transition_with_presence(
                    transition_lm_index,
                    context_suffix,
                    alt_word,
                    segment.is_rear,
                    weights,
                )
                alt_next_suffix = build_context_suffix(
                    context_suffix, alt_word, context_token_limit
                )
                alt_next_ctx = 0.0
                alt_next_has = False
                if next_word:
                    alt_next_ctx, _, alt_next_has = score_transition_with_presence(
                        transition_lm_index,
                        alt_next_suffix,
                        next_word,
                        next_is_rear,
                        weights,
                    )
                alt_has_signal = alt_curr_has or alt_next_has
                if not alt_has_signal and not chosen_has_signal:
                    continue
                base_diff = alt_base - chosen_base
                ctx_diff = (alt_curr_ctx + alt_next_ctx) - chosen_total_ctx
                gain = base_diff + ctx_diff * weights.ctx_local_scale
                if gain > best_gain and gain > weights.ctx_local_gain_threshold:
                    best_gain = gain
                    best_word = alt_word
                    best_dict_weight = float(candidate.get("weight", 0.0) or 0.0)
                    best_debug = (
                        f"local_ctx replace start={segment.start} end={segment.end} "
                        f"{segment.word}->{alt_word} base_diff={base_diff:.3f} "
                        f"ctx_diff={ctx_diff:.3f} scale={weights.ctx_local_scale:.3f} "
                        f"gain={gain:.3f}"
                    )
        chosen_word = best_word
        chosen_dict_weight = best_dict_weight
        total_gain += best_gain
        debug_parts.append(best_debug)
        updated_words.append(chosen_word)
        updated_segments.append(
            PathSegment(
                start=segment.start,
                end=segment.end,
                word=chosen_word,
                dict_weight=chosen_dict_weight,
                edge_risk=segment.edge_risk,
                edge_spelling_class=segment.edge_spelling_class,
                vertex_risk=segment.vertex_risk,
                is_rear=segment.is_rear,
            )
        )
        context_suffix = build_context_suffix(context_suffix, chosen_word, context_token_limit)
    return PathState(
        score=state.score + total_gain,
        text="".join(updated_words),
        words=updated_words,
        debug_parts=debug_parts,
        segments=updated_segments,
        context_suffix=context_suffix,
        last_word_len_class=state.last_word_len_class,
        trailing_single_char_run=state.trailing_single_char_run,
        recent_len_signature=state.recent_len_signature,
    )


def compute_path_context_rerank(
    state: PathState,
    transition_lm_index: dict[tuple[str, str, bool], dict[str, Any]],
    context_token_limit: int,
    weights: SolverWeights,
) -> tuple[float, list[str], str]:
    context_suffix = ""
    total_ctx_score = 0.0
    debug_parts: list[str] = []
    word_count = len(state.words)
    for index, word in enumerate(state.words):
        is_rear = index == word_count - 1
        transition_key = make_transition_key(context_suffix, word, is_rear)
        ctx_score, ctx_debug = score_transition_context(
            transition_lm_index.get(transition_key), weights
        )
        total_ctx_score += ctx_score
        debug_parts.append(
            f"rerank[{index}] word={word} suffix={context_suffix or '<root>'} {ctx_debug}"
        )
        context_suffix = build_context_suffix(context_suffix, word, context_token_limit)
    return total_ctx_score, debug_parts, context_suffix


def score_word_edge_c01(
    candidate: dict[str, Any],
    edge_risk: float,
    edge_spelling_class: int,
    vertex_risk: float,
    weights: SolverWeights,
    state: PathState,
) -> tuple[float, str, int, int, str]:
    score, debug = score_word_edge(
        candidate, edge_risk, edge_spelling_class, vertex_risk, weights
    )
    text = str(candidate.get("text", ""))
    char_count = max(1, utf8_char_count(text))
    current_len_class = length_class(char_count)
    next_trailing_single_char_run = (
        min(3, state.trailing_single_char_run + 1) if char_count == 1 else 0
    )
    recent_signature = update_recent_len_signature(
        state.recent_len_signature, current_len_class
    )

    state_adjustment = 0.0
    if char_count == 1 and state.last_word_len_class >= 2:
        state_adjustment -= 0.45 + 0.25 * float(state.trailing_single_char_run)
    if char_count == 1 and state.trailing_single_char_run >= 1:
        state_adjustment -= 0.35 * float(state.trailing_single_char_run)
    if char_count >= 2 and state.trailing_single_char_run >= 2:
        state_adjustment += 0.30
    if recent_signature == "1-1":
        state_adjustment -= 0.30
    elif recent_signature == "3-1":
        state_adjustment -= 0.20
    elif recent_signature == "2-2":
        state_adjustment += 0.10

    score += state_adjustment
    debug += (
        f" state_adj={state_adjustment:.3f} last_len={state.last_word_len_class} "
        f"trail1={state.trailing_single_char_run} recent={state.recent_len_signature or 'root'}"
    )
    return (
        score,
        debug,
        current_len_class,
        next_trailing_single_char_run,
        recent_signature,
    )


def solve_graph_record(
    record: dict[str, Any], weights: SolverWeights, top_k: int
) -> list[PathState]:
    interpreted_length = int(record.get("interpreted_length", 0) or 0)
    vertex_risks = {
        int(vertex.get("pos", 0)): float(vertex.get("risk", 0.0) or 0.0)
        for vertex in record.get("vertices", [])
        if isinstance(vertex, dict)
    }
    word_edges_by_start = build_word_edges_by_start(record)

    best_states: dict[int, list[PathState]] = {
        0: [PathState(score=0.0, text="", words=[], debug_parts=[], context_suffix="")]
    }
    for pos in range(interpreted_length + 1):
        states = best_states.get(pos) or []
        if not states:
            continue
        for edge in word_edges_by_start.get(pos, []):
            end = int(edge.get("end", pos) or pos)
            edge_risk = float(edge.get("edge_risk", 0.0) or 0.0)
            edge_spelling_class = int(edge.get("edge_spelling_class", 0) or 0)
            vertex_risk = vertex_risks.get(end, 0.0)
            candidates = edge.get("candidates", [])
            if not isinstance(candidates, list):
                continue
            for state in states:
                for candidate in candidates:
                    if not isinstance(candidate, dict):
                        continue
                    delta_score, debug = score_word_edge(
                        candidate, edge_risk, edge_spelling_class, vertex_risk, weights
                    )
                    word = str(candidate.get("text", ""))
                    next_state = PathState(
                        score=state.score + delta_score,
                        text=state.text + word,
                        words=state.words + [word],
                        debug_parts=state.debug_parts + [f"{pos}->{end} {debug}"],
                        segments=state.segments
                        + [
                            PathSegment(
                                start=pos,
                                end=end,
                                word=word,
                                dict_weight=float(candidate.get("weight", 0.0) or 0.0),
                                edge_risk=edge_risk,
                                edge_spelling_class=edge_spelling_class,
                                vertex_risk=vertex_risk,
                                is_rear=(end == interpreted_length),
                            )
                        ],
                        context_suffix="",
                    )
                    bucket = best_states.setdefault(end, [])
                    bucket.append(next_state)
                    bucket.sort(key=lambda item: item.score, reverse=True)
                    del bucket[top_k:]
    finals = best_states.get(interpreted_length, [])
    finals.sort(key=lambda item: item.score, reverse=True)
    return finals


def solve_graph_record_c0_ctx(
    record: dict[str, Any], weights: SolverWeights, top_k: int
) -> list[PathState]:
    interpreted_length = int(record.get("interpreted_length", 0) or 0)
    transition_lm_index, context_token_limit = build_transition_lm_index(record)
    vertex_risks = {
        int(vertex.get("pos", 0)): float(vertex.get("risk", 0.0) or 0.0)
        for vertex in record.get("vertices", [])
        if isinstance(vertex, dict)
    }
    word_edges_by_start: dict[int, list[dict[str, Any]]] = {}
    for edge in record.get("word_edges", []):
        if not isinstance(edge, dict):
            continue
        word_edges_by_start.setdefault(int(edge.get("start", 0) or 0), []).append(edge)

    best_states: dict[int, list[PathState]] = {
        0: [PathState(score=0.0, text="", words=[], debug_parts=[], context_suffix="")]
    }
    for pos in range(interpreted_length + 1):
        states = best_states.get(pos) or []
        if not states:
            continue
        for edge in word_edges_by_start.get(pos, []):
            end = int(edge.get("end", pos) or pos)
            edge_risk = float(edge.get("edge_risk", 0.0) or 0.0)
            edge_spelling_class = int(edge.get("edge_spelling_class", 0) or 0)
            vertex_risk = vertex_risks.get(end, 0.0)
            is_rear = end == interpreted_length
            candidates = edge.get("candidates", [])
            if not isinstance(candidates, list):
                continue
            for state in states:
                for candidate in candidates:
                    if not isinstance(candidate, dict):
                        continue
                    delta_score, debug = score_word_edge(
                        candidate, edge_risk, edge_spelling_class, vertex_risk, weights
                    )
                    word = str(candidate.get("text", ""))
                    transition_key = make_transition_key(
                        state.context_suffix, word, is_rear
                    )
                    ctx_score, ctx_debug = score_transition_context(
                        transition_lm_index.get(transition_key), weights
                    )
                    next_context_suffix = build_context_suffix(
                        state.context_suffix, word, context_token_limit
                    )
                    next_state = PathState(
                        score=state.score + delta_score + ctx_score,
                        text=state.text + word,
                        words=state.words + [word],
                        debug_parts=state.debug_parts
                        + [f"{pos}->{end} {debug} {ctx_debug}"],
                        context_suffix=next_context_suffix,
                    )
                    bucket = best_states.setdefault(end, [])
                    bucket.append(next_state)
                    bucket.sort(key=lambda item: item.score, reverse=True)
                    del bucket[top_k:]
    finals = best_states.get(interpreted_length, [])
    finals.sort(key=lambda item: item.score, reverse=True)
    return finals


def solve_graph_record_c0_ctx_rerank(
    record: dict[str, Any], weights: SolverWeights, top_k: int
) -> list[PathState]:
    expanded_top_k = max(top_k * 4, 16)
    base_results = solve_graph_record(record, weights, expanded_top_k)
    if not base_results:
        return []
    transition_lm_index, context_token_limit = build_transition_lm_index(record)
    best_base_score = base_results[0].score
    reranked_results: list[PathState] = []
    for state in base_results:
        ctx_total, ctx_debug_parts, final_context_suffix = compute_path_context_rerank(
            state, transition_lm_index, context_token_limit, weights
        )
        within_margin = state.score >= best_base_score - weights.ctx_rerank_margin
        rerank_bonus = (
            ctx_total * weights.ctx_rerank_scale if within_margin else 0.0
        )
        rerank_note = (
            f"rerank base={state.score:.3f} ctx_total={ctx_total:.3f} "
            f"scale={weights.ctx_rerank_scale:.3f} "
            f"margin={weights.ctx_rerank_margin:.3f} "
            f"applied={int(within_margin)} bonus={rerank_bonus:.3f} "
            f"final={state.score + rerank_bonus:.3f}"
        )
        reranked_results.append(
            PathState(
                score=state.score + rerank_bonus,
                text=state.text,
                words=state.words,
                debug_parts=state.debug_parts + [rerank_note] + ctx_debug_parts,
                context_suffix=final_context_suffix,
                last_word_len_class=state.last_word_len_class,
                trailing_single_char_run=state.trailing_single_char_run,
                recent_len_signature=state.recent_len_signature,
            )
        )
    reranked_results.sort(key=lambda item: item.score, reverse=True)
    return reranked_results[: max(top_k * 3, 12)]


def solve_graph_record_c0_ctx_local(
    record: dict[str, Any], weights: SolverWeights, top_k: int
) -> list[PathState]:
    base_results = solve_graph_record(record, weights, max(top_k * 4, 16))
    if not base_results:
        return []
    transition_lm_index, context_token_limit = build_transition_lm_index(record)
    word_edges_by_start = build_word_edges_by_start(record)
    localized_results = [
        apply_local_context_substitutions(
            state,
            word_edges_by_start,
            transition_lm_index,
            context_token_limit,
            weights,
        )
        for state in base_results
    ]
    localized_results.sort(key=lambda item: item.score, reverse=True)
    return localized_results[: max(top_k * 3, 12)]


def solve_graph_record_c0_ctx_local_top1(
    record: dict[str, Any], weights: SolverWeights, top_k: int
) -> list[PathState]:
    base_results = solve_graph_record(record, weights, max(top_k * 4, 16))
    if not base_results:
        return []
    transition_lm_index, context_token_limit = build_transition_lm_index(record)
    word_edges_by_start = build_word_edges_by_start(record)
    anchor = base_results[0]
    localized_anchor = apply_local_context_substitutions(
        anchor,
        word_edges_by_start,
        transition_lm_index,
        context_token_limit,
        weights,
        require_nonnegative_base_diff=True,
    )
    combined_results: list[PathState] = [anchor]
    if (
        localized_anchor.text != anchor.text
        or localized_anchor.score != anchor.score
        or localized_anchor.debug_parts != anchor.debug_parts
    ):
        combined_results.append(localized_anchor)
    combined_results.extend(base_results[1 : max(top_k * 3, 12)])
    combined_results.sort(key=lambda item: item.score, reverse=True)
    return combined_results[: max(top_k * 3, 12)]


def solve_graph_record_c01(
    record: dict[str, Any], weights: SolverWeights, top_k: int
) -> list[PathState]:
    interpreted_length = int(record.get("interpreted_length", 0) or 0)
    vertex_risks = {
        int(vertex.get("pos", 0)): float(vertex.get("risk", 0.0) or 0.0)
        for vertex in record.get("vertices", [])
        if isinstance(vertex, dict)
    }
    word_edges_by_start: dict[int, list[dict[str, Any]]] = {}
    for edge in record.get("word_edges", []):
        if not isinstance(edge, dict):
            continue
        word_edges_by_start.setdefault(int(edge.get("start", 0) or 0), []).append(edge)

    best_states: dict[int, dict[str, list[PathState]]] = {
        0: {
            "root": [
                PathState(
                    score=0.0,
                    text="",
                    words=[],
                    debug_parts=[],
                    last_word_len_class=0,
                    trailing_single_char_run=0,
                    recent_len_signature="",
                )
            ]
        }
    }
    for pos in range(interpreted_length + 1):
        state_groups = best_states.get(pos) or {}
        if not state_groups:
            continue
        flat_states: list[PathState] = []
        for group_states in state_groups.values():
            flat_states.extend(group_states)
        for edge in word_edges_by_start.get(pos, []):
            end = int(edge.get("end", pos) or pos)
            edge_risk = float(edge.get("edge_risk", 0.0) or 0.0)
            edge_spelling_class = int(edge.get("edge_spelling_class", 0) or 0)
            vertex_risk = vertex_risks.get(end, 0.0)
            candidates = edge.get("candidates", [])
            if not isinstance(candidates, list):
                continue
            for state in flat_states:
                for candidate in candidates:
                    if not isinstance(candidate, dict):
                        continue
                    (
                        delta_score,
                        debug,
                        current_len_class,
                        next_trailing_single_char_run,
                        recent_signature,
                    ) = score_word_edge_c01(
                        candidate,
                        edge_risk,
                        edge_spelling_class,
                        vertex_risk,
                        weights,
                        state,
                    )
                    word = str(candidate.get("text", ""))
                    next_state = PathState(
                        score=state.score + delta_score,
                        text=state.text + word,
                        words=state.words + [word],
                        debug_parts=state.debug_parts + [f"{pos}->{end} {debug}"],
                        last_word_len_class=current_len_class,
                        trailing_single_char_run=next_trailing_single_char_run,
                        recent_len_signature=recent_signature,
                    )
                    state_key = (
                        f"{current_len_class}|{next_trailing_single_char_run}|"
                        f"{recent_signature or 'root'}"
                    )
                    end_groups = best_states.setdefault(end, {})
                    bucket = end_groups.setdefault(state_key, [])
                    bucket.append(next_state)
                    bucket.sort(key=lambda item: item.score, reverse=True)
                    del bucket[top_k:]
        if pos in best_states:
            end_groups = best_states[pos]
            trimmed_groups: dict[str, list[PathState]] = {}
            for state_key, bucket in end_groups.items():
                trimmed_groups[state_key] = bucket[:top_k]
            best_states[pos] = trimmed_groups

    finals: list[PathState] = []
    for bucket in (best_states.get(interpreted_length) or {}).values():
        finals.extend(bucket)
    finals.sort(key=lambda item: item.score, reverse=True)
    return finals[: max(top_k * 3, 12)]


def solve_graph_record_c01_state_only(
    record: dict[str, Any], weights: SolverWeights, top_k: int
) -> list[PathState]:
    interpreted_length = int(record.get("interpreted_length", 0) or 0)
    vertex_risks = {
        int(vertex.get("pos", 0)): float(vertex.get("risk", 0.0) or 0.0)
        for vertex in record.get("vertices", [])
        if isinstance(vertex, dict)
    }
    word_edges_by_start: dict[int, list[dict[str, Any]]] = {}
    for edge in record.get("word_edges", []):
        if not isinstance(edge, dict):
            continue
        word_edges_by_start.setdefault(int(edge.get("start", 0) or 0), []).append(edge)

    best_states: dict[int, dict[str, list[PathState]]] = {
        0: {
            "root": [
                PathState(
                    score=0.0,
                    text="",
                    words=[],
                    debug_parts=[],
                    last_word_len_class=0,
                    trailing_single_char_run=0,
                    recent_len_signature="",
                )
            ]
        }
    }
    for pos in range(interpreted_length + 1):
        state_groups = best_states.get(pos) or {}
        if not state_groups:
            continue
        flat_states: list[PathState] = []
        for group_states in state_groups.values():
            flat_states.extend(group_states)
        for edge in word_edges_by_start.get(pos, []):
            end = int(edge.get("end", pos) or pos)
            edge_risk = float(edge.get("edge_risk", 0.0) or 0.0)
            edge_spelling_class = int(edge.get("edge_spelling_class", 0) or 0)
            vertex_risk = vertex_risks.get(end, 0.0)
            candidates = edge.get("candidates", [])
            if not isinstance(candidates, list):
                continue
            for state in flat_states:
                for candidate in candidates:
                    if not isinstance(candidate, dict):
                        continue
                    delta_score, debug = score_word_edge(
                        candidate, edge_risk, edge_spelling_class, vertex_risk, weights
                    )
                    word = str(candidate.get("text", ""))
                    char_count = max(1, utf8_char_count(word))
                    current_len_class = length_class(char_count)
                    next_trailing_single_char_run = (
                        min(3, state.trailing_single_char_run + 1)
                        if char_count == 1
                        else 0
                    )
                    recent_signature = update_recent_len_signature(
                        state.recent_len_signature, current_len_class
                    )
                    next_state = PathState(
                        score=state.score + delta_score,
                        text=state.text + word,
                        words=state.words + [word],
                        debug_parts=state.debug_parts + [f"{pos}->{end} {debug}"],
                        last_word_len_class=current_len_class,
                        trailing_single_char_run=next_trailing_single_char_run,
                        recent_len_signature=recent_signature,
                    )
                    state_key = (
                        f"{current_len_class}|{next_trailing_single_char_run}|"
                        f"{recent_signature or 'root'}"
                    )
                    end_groups = best_states.setdefault(end, {})
                    bucket = end_groups.setdefault(state_key, [])
                    bucket.append(next_state)
                    bucket.sort(key=lambda item: item.score, reverse=True)
                    del bucket[top_k:]

    finals: list[PathState] = []
    for bucket in (best_states.get(interpreted_length) or {}).values():
        finals.extend(bucket)
    finals.sort(key=lambda item: item.score, reverse=True)
    return finals[: max(top_k * 3, 12)]


def build_reference_index(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    ordered = [record for record in records if isinstance(record, dict)]
    ordered.sort(key=lambda item: int(item.get("step_index", 0) or 0))
    return ordered


def build_graph_index(records: list[dict[str, Any]]) -> dict[tuple[str, str], dict[str, Any]]:
    index: dict[tuple[str, str], dict[str, Any]] = {}
    for record in records:
        key = (str(record.get("input", "")), str(record.get("preceding_text", "")))
        index[key] = record
    return index


def build_graph_input_index(records: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    index: dict[str, dict[str, Any]] = {}
    for record in records:
        index[str(record.get("input", ""))] = record
    return index


def build_graph_indices_for_inputs(
    graph_path: Path, target_inputs: set[str]
) -> tuple[
    dict[tuple[str, str], dict[str, Any]],
    dict[str, dict[str, Any]],
    int,
    int | None,
    int | None,
]:
    graph_index: dict[tuple[str, str], dict[str, Any]] = {}
    graph_input_index: dict[str, dict[str, Any]] = {}
    graph_record_count = 0
    first_timestamp_ms: int | None = None
    last_timestamp_ms: int | None = None
    for record in iter_jsonl_records(graph_path):
        graph_record_count += 1
        timestamp = record.get("timestamp_ms")
        if isinstance(timestamp, (int, float)):
            ts_value = int(timestamp)
            if first_timestamp_ms is None or ts_value < first_timestamp_ms:
                first_timestamp_ms = ts_value
            if last_timestamp_ms is None or ts_value > last_timestamp_ms:
                last_timestamp_ms = ts_value
        record_input = str(record.get("input", ""))
        if record_input not in target_inputs:
            continue
        record_preceding = str(record.get("preceding_text", ""))
        graph_index[(record_input, record_preceding)] = record
        graph_input_index[record_input] = record
    return (
        graph_index,
        graph_input_index,
        graph_record_count,
        first_timestamp_ms,
        last_timestamp_ms,
    )


def file_metadata(path: Path) -> dict[str, Any]:
    stat = path.stat()
    return {
        "path": str(path),
        "size_bytes": stat.st_size,
        "last_modified_iso": datetime.fromtimestamp(stat.st_mtime).isoformat(),
    }


def extract_timestamp_bounds(records: list[dict[str, Any]]) -> tuple[int | None, int | None]:
    timestamps = [
        int(record.get("timestamp_ms", 0) or 0)
        for record in records
        if isinstance(record.get("timestamp_ms"), (int, float))
    ]
    if not timestamps:
        return None, None
    return min(timestamps), max(timestamps)


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        json.dump(payload, handle, ensure_ascii=False, indent=2)
        handle.write("\n")


def write_markdown(path: Path, summary: dict[str, Any], mismatches: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# C0 Graph Solver Summary",
        "",
        "## Metrics",
        "",
        f"- Evaluated cases: {summary['evaluated_case_count']}",
        f"- Missing graph cases: {summary['missing_graph_case_count']}",
        f"- Top-1 hits: {summary['top1_hit_count']}",
        f"- Top-3 hits: {summary['top3_hit_count']}",
        f"- Top-1 accuracy: {summary['top1_accuracy']:.6f}",
        f"- Top-3 accuracy: {summary['top3_accuracy']:.6f}",
        f"- Match by preceding_text: {summary['match_by_preceding_count']}",
        f"- Match by snapshot_preceding_text: {summary['match_by_snapshot_preceding_count']}",
        f"- Match by input only: {summary['match_by_input_only_count']}",
        "",
        "## Top-1 Mismatches",
        "",
    ]
    if not mismatches:
        lines.append("- None")
    else:
        for item in mismatches[:30]:
            lines.append(
                f"- {item['input']} -> top1={item['top1_text']} | expected={item['expected_text']}"
            )
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    args = parse_args()
    graph_path = Path(args.graph).expanduser().resolve()
    reference_path = Path(args.reference).expanduser().resolve()
    output_json = Path(args.output_json).expanduser().resolve()
    output_md = Path(args.output_md).expanduser().resolve()

    if not graph_path.is_file():
        raise SystemExit(f"Graph snapshot not found: {graph_path}")
    if not reference_path.is_file():
        raise SystemExit(f"Reference file not found: {reference_path}")

    weights = SolverWeights()
    references = build_reference_index(load_jsonl(reference_path))
    if args.input:
        references = [record for record in references if record.get("input") == args.input]
    if args.limit is not None:
        references = references[: args.limit]
    target_inputs = {str(reference.get("input", "")) for reference in references}
    (
        graph_index,
        graph_input_index,
        graph_record_count,
        graph_first_ts,
        graph_last_ts,
    ) = build_graph_indices_for_inputs(graph_path, target_inputs)

    summary: dict[str, Any] = {
        "graph": str(graph_path),
        "reference": str(reference_path),
        "solver": args.solver,
        "graph_record_count": graph_record_count,
        "reference_case_count": len(references),
        "graph_file": file_metadata(graph_path),
        "reference_file": file_metadata(reference_path),
        "evaluated_case_count": 0,
        "missing_graph_case_count": 0,
        "top1_hit_count": 0,
        "top3_hit_count": 0,
        "top1_accuracy": 0.0,
        "top3_accuracy": 0.0,
        "match_by_preceding_count": 0,
        "match_by_snapshot_preceding_count": 0,
        "match_by_input_only_count": 0,
        "weights": weights.__dict__,
        "warnings": [],
    }
    summary["graph_first_timestamp_ms"] = graph_first_ts
    summary["graph_last_timestamp_ms"] = graph_last_ts
    details: list[dict[str, Any]] = []
    top1_hits = 0
    top3_hits = 0

    for reference in references:
        key = (str(reference.get("input", "")), str(reference.get("preceding_text", "")))
        match_strategy = "preceding_text"
        graph_record = graph_index.get(key)
        if graph_record is None:
            fallback_key = (
                str(reference.get("input", "")),
                str(reference.get("snapshot_preceding_text", "")),
            )
            graph_record = graph_index.get(fallback_key)
            if graph_record is not None:
                match_strategy = "snapshot_preceding_text"
        if graph_record is None:
            graph_record = graph_input_index.get(str(reference.get("input", "")))
            if graph_record is not None:
                match_strategy = "input_only"
        if graph_record is None:
            summary["missing_graph_case_count"] += 1
            continue
        summary["evaluated_case_count"] += 1
        if match_strategy == "preceding_text":
            summary["match_by_preceding_count"] += 1
        elif match_strategy == "snapshot_preceding_text":
            summary["match_by_snapshot_preceding_count"] += 1
        else:
            summary["match_by_input_only_count"] += 1
        if args.solver == "c01":
            results = solve_graph_record_c01(graph_record, weights, max(1, args.top_k))
        elif args.solver == "c0_ctx":
            results = solve_graph_record_c0_ctx(
                graph_record, weights, max(1, args.top_k)
            )
        elif args.solver == "c0_ctx_rerank":
            results = solve_graph_record_c0_ctx_rerank(
                graph_record, weights, max(1, args.top_k)
            )
        elif args.solver == "c0_ctx_local":
            results = solve_graph_record_c0_ctx_local(
                graph_record, weights, max(1, args.top_k)
            )
        elif args.solver == "c0_ctx_local_top1":
            results = solve_graph_record_c0_ctx_local_top1(
                graph_record, weights, max(1, args.top_k)
            )
        elif args.solver == "c01_state_only":
            results = solve_graph_record_c01_state_only(
                graph_record, weights, max(1, args.top_k)
            )
        else:
            results = solve_graph_record(graph_record, weights, max(1, args.top_k))
        top_texts = [state.text for state in results[:3]]
        expected_text = str(reference.get("expected_text", ""))
        top1_text = top_texts[0] if top_texts else ""
        top1_hit = top1_text == expected_text
        top3_hit = expected_text in top_texts
        if top1_hit:
            top1_hits += 1
        if top3_hit:
            top3_hits += 1
        details.append(
            {
                "case_id": reference.get("case_id"),
                "input": reference.get("input"),
                "preceding_text": reference.get("preceding_text"),
                "expected_text": expected_text,
                "top1_text": top1_text,
                "top3_texts": top_texts,
                "top1_hit": top1_hit,
                "top3_hit": top3_hit,
                "match_strategy": match_strategy,
                "best_path_debug": results[0].debug_parts if results else [],
            }
        )

    evaluated = int(summary["evaluated_case_count"])
    summary["top1_hit_count"] = top1_hits
    summary["top3_hit_count"] = top3_hits
    if evaluated > 0:
        summary["top1_accuracy"] = top1_hits / evaluated
        summary["top3_accuracy"] = top3_hits / evaluated
    reference_case_count = int(summary["reference_case_count"])
    coverage_ratio = (evaluated / reference_case_count) if reference_case_count > 0 else 0.0
    summary["coverage_ratio"] = coverage_ratio
    warnings: list[str] = []
    graph_mtime = graph_path.stat().st_mtime
    reference_mtime = reference_path.stat().st_mtime
    if coverage_ratio < 0.95:
        warnings.append(
            f"Low graph coverage: evaluated {evaluated}/{reference_case_count} "
            f"({coverage_ratio:.3f})."
        )
    if graph_mtime > reference_mtime + 60:
        warnings.append(
            "Graph snapshot is newer than reference_cases; artifacts may come "
            "from different baseline runs."
        )
    elif reference_mtime > graph_mtime + 60:
        warnings.append(
            "Reference cases are newer than graph snapshot; artifacts may come "
            "from different baseline runs."
        )
    summary["warnings"] = warnings
    mismatches = [item for item in details if not item["top1_hit"]]
    write_json(output_json, {"summary": summary, "details": details})
    write_markdown(output_md, summary, mismatches)
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print(f"JSON summary written to: {output_json}")
    print(f"Markdown summary written to: {output_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
